### PR TITLE
Feature/ip addresses discovery

### PR DESCRIPTION
**Pull request by rekup**
* add option generate targers from plain ip addresses (opt in via `NETBOX_OBJECTS` env var)

### CODE REVIEW

**Comment by FlxPeters** [comment]
Thanks for your contribution. Code looks good. 
The checks fail due to errors in my Sonarqube config. I will fix that later in another MR.

**Comment by FlxPeters** [comment]
@rekup Do you need a fast release for this change? I have some issues for the next release, but i can add another one if you have demand.

**Comment by rekup** [comment]
Thanks for asking! A new release within the next few weeks would be nice but no need to hurry

**Comment by rekup** [comment]
Also, if you would like some help on some issues let me know / tag the issues. I'd be glad to contribute

**Pull request merged**
